### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by NirantK** [cs109/2015#4]
The link https://github.com/cs109-students/2015hw in the README is broken. Please replace with the updated link.

**Comment by imnishantg** [comment]
HI CS109 team

I could not find links to homeworks (as Nirant mentions above).
Could you share the link to which homework is uploaded?

Thanks in advance
Nishant

**Comment by rahuldave** [comment]
Its not broken, you should be able to access it if you accepted the invites from github and are in the cs109-students organization.  Once you get there, the homeworks are in branches.

But you should be getting your homework from the repository:

cs109-students/yourgithubusername-2015hw

**Comment by imnishantg** [comment]
Hi Rahul
I'm not affiliated with Harvard in any way. I'm taking this course by viewing publicly available videos and other material.
Is there a way to access the homework by someone outside the cs109-students organization... or was this all a part of HW0?
Thanks for replying

**Comment by rahuldave** [comment]
The homeworks are private to registered students this year, unfortunately.
You are still welcome to the labs, all of which are in repos cs109/2015labx
where x=1,2,3.... Previous years homeworks are still available. All
lectures are available on the web site!

On Fri, Sep 18, 2015 at 4:42 PM, Nishant Gupta notifications@github.com
wrote:

> Hi Rahul
> I'm not affiliated with Harvard in any way. I'm taking this course by
> viewing publicly available videos and other material.
> Is there a way to access the homework by someone outside the
> cs109-students organization... or was this all a part of HW0?
> Thanks for replying
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cs109/2015/issues/4#issuecomment-141563162.

## 

Dr. Rahul Dave
LxPrior Inc. and Harvard University
rahuldave@gmail.com
(રાહુલ દવે)

**Comment by koustuvsinha** [comment]
@rahuldave any timeline when the homeworks will be public since the course is over now? would very much like to try them out

**Comment by Le0nX** [comment]
hello, I'm from future. There is still no homeworks 2015...
